name: ci

on: [push]

jobs:
  dependencies:
    name: setup node & install deps
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v5
      - &setup-node
        name: node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: install dependencies
        run: npm ci

  changeset:
    name: changeset
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v5
      - *setup-node
      - run: npm ci
      - run: npm run check:changeset

  types:
    name: types
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v5
      - *setup-node
      - run: npm ci
      - run: npm run check:types

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v5
      - *setup-node
      - run: npm ci
      - run: npm run lint

  test:
    name: test
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v5
      - *setup-node
      - run: npm ci
      - run: npm run test

  build:
    name: build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v5
      - *setup-node
      - run: npm ci
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist