name: Push

on: push

jobs:
  deps:
    name: install deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules
          retention-days: 1

  changeset:
    name: changeset
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - run: npm run check:changeset

  types:
    name: check:types
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - run: npm run check:types

  lint:
    name: check:lint
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - run: npm rebuild eslint && npm run lint

  test:
    name: tests
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - run: npm rebuild jest && npm run test

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [changeset, types, lint, test]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - run: npm rebuild rolldown && npm run build
